compute_environment: LOCAL_MACHINE
debug: false
distributed_training: MULTI_GPU
downcast_bf16: 'no'
gpu_ids: all
machine_rank: 0
main_training_function: main
mixed_precision: bf16
num_processes: 4
num_machines: 1
rdzv_backend: static
same_net_work: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
